name: param_lattice
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip>=24
  - numpy
  - scipy
  - pandas
  - plotly
  - xlwings
  - pytest
  - pint
  - jaxtyping
  - dacite
  - pip:
      - "-e .[all,dev]"
      - ansys-mapdl-core